### ISSUE TITLE
how did you get the wheel file?

### ISSUE THREAD

**Issue by hoangdzung** [lherman-cs/tensorflow-aarch64#4]
First of all, thank you very much for your repo. I have followed the instruction in tensorflow official webpage. It took me several days because of bunch of errors and still failed to install. Now, I follow your guide and be successful to use it.
Can you show me the way you create the wheel file? I used bazel to make it but failed. I got this error: 

`Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
from tensorflow.python import * # pylint: disable=redefined-builtin
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/usr/lib/python3.5/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN3Aws11Environment6GetEnvB5cxx11EPKc`

**Comment by lherman-cs** [comment]
I'm so sorry. I've been really busy with school and work. I'm not maintaining this repo anymore. But, if you have an automation script for building it. I'm welcome with contributions!

**Comment by lherman-cs** [comment]
It looks like that there was an issue with your compilation. Are you sure that there was no error at all during the compilation because it seems to me that it's missing the required dynamic library.
